import Link from "next/link";
import {headers} from "next/headers";
import {notFound} from "next/navigation";
import {ResourceCreatePanel} from "@/components/back-office/resource-create-panel";
import {SettingsForm} from "@/components/back-office/settings-form";
import {auth} from "@/lib/auth";
import {listBackOfficeRows} from "@/lib/repositories/back-office";
import {getCompanySettings} from "@/lib/repositories/public-content";

const sections=["pages","investor-documents","vacancies","applications","messages","media","navigation","footer","settings","users"];
export const dynamic="force-dynamic";
export default async function Section({params,searchParams}:{params:Promise<{section:string}>;searchParams:Promise<{q?:string;status?:string;page?:string}>}){
  const {section}=await params;if(!sections.includes(section))notFound();
  const session=await auth.api.getSession({headers:await headers()});if(!session)notFound();if(section==="users"&&session.user.role!=="SUPER_ADMIN")notFound();
  const title=section.split("-").map(x=>x[0].toUpperCase()+x.slice(1)).join(" ");
  if(section==="settings")return <><nav className="mb-2 text-sm text-slate-500">Dashboard / Settings</nav><h1 className="text-3xl font-black">Settings</h1><SettingsForm value={await getCompanySettings()}/></>;
  const allRows=await listBackOfficeRows(section);const query=await searchParams;const q=query.q?.trim().toLowerCase()??"";const filtered=allRows.filter(row=>(!q||`${row.title} ${row.meta}`.toLowerCase().includes(q))&&(!query.status||row.status===query.status));const page=Math.max(1,Number(query.page)||1),perPage=20,totalPages=Math.max(1,Math.ceil(filtered.length/perPage));const rows=filtered.slice((page-1)*perPage,page*perPage);const statuses=[...new Set(allRows.map(row=>row.status))];const hasDetail=["pages","applications","messages","investor-documents","vacancies","users","media"].includes(section);const pageUrl=(next:number)=>`/back-office/${section}?${new URLSearchParams({...(query.q?{q:query.q}:{}),...(query.status?{status:query.status}:{}),page:String(next)})}`;
  return <><nav className="mb-2 text-sm text-slate-500">Dashboard / {title}</nav><div className="relative flex items-center justify-between"><h1 className="text-3xl font-black">{title}</h1><ResourceCreatePanel section={section}/></div><form className="mt-6 flex flex-wrap gap-3"><input name="q" defaultValue={query.q} placeholder="Search" className="min-h-11 rounded border px-3"/><select name="status" defaultValue={query.status} className="min-h-11 rounded border px-3"><option value="">All statuses</option>{statuses.map(status=><option key={status}>{status}</option>)}</select><button className="btn btn-primary">Filter</button></form><div className="mt-5 overflow-x-auto rounded-lg border bg-white"><table className="w-full text-left"><thead className="border-b bg-slate-50 text-sm"><tr><th className="p-4">Name</th><th className="p-4">Details</th><th className="p-4">Status</th><th className="p-4">Action</th></tr></thead><tbody>{rows.map(row=><tr className="border-b last:border-0" key={row.id}><td className="p-4 font-semibold">{row.title}</td><td className="p-4 text-sm text-slate-600">{row.meta}</td><td className="p-4"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{row.status}</span></td><td className="p-4">{hasDetail?<Link className="font-semibold text-blue-600" href={`/back-office/${section}/${row.id}`}>View</Link>:<span className="text-slate-400">Listed</span>}</td></tr>)}</tbody></table>{rows.length===0&&<p className="p-10 text-center text-slate-500">No records found.</p>}</div><nav aria-label="Pagination" className="mt-4 flex items-center justify-between"><Link aria-disabled={page===1} className={page===1?"pointer-events-none text-slate-400":"text-blue-600"} href={pageUrl(page-1)}>Previous</Link><span className="text-sm">Page {page} of {totalPages}</span><Link aria-disabled={page>=totalPages} className={page>=totalPages?"pointer-events-none text-slate-400":"text-blue-600"} href={pageUrl(page+1)}>Next</Link></nav></>;
}
